name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      maxRetry:
        description: "Maximum number of retries"
        required: false
        default: "2"

jobs:
  # First Attempt
  setup-1:
    uses: ./.github/workflows/setup.yml

  smoke-1:
    needs: setup-1
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.smoke-test.outcome }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Smoke Tests
        id: smoke-test
        run: |
          chmod +x ./scripts/smoke-test.sh
          ./scripts/smoke-test.sh

  run-1:
    needs: smoke-1
    uses: ./.github/workflows/run-go-example.yml
    with:
      is_retry: false
      fail_on_error: false
      success_percentage: 0

  teardown-1:
    needs: run-1
    uses: ./.github/workflows/teardown.yml

  # Second Attempt (Retry)
  setup-2:
    needs: [teardown-1, run-1]
    if: needs.run-1.outputs.execution-result == 'failure'
    uses: ./.github/workflows/setup.yml

  smoke-2:
    needs: setup-2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Smoke Tests
        id: smoke-test
        run: |
          chmod +x ./scripts/smoke-test.sh
          ./scripts/smoke-test.sh

  run-2:
    needs: smoke-2
    uses: ./.github/workflows/run-go-example.yml
    with:
      is_retry: true
      fail_on_error: true
      success_percentage: 0

  teardown-2:
    needs: run-2
    uses: ./.github/workflows/teardown.yml

  # Final Report
  generate-report-1:
    needs: [run-1, smoke-1]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Generate Report
        run: |
          echo "Execution Report 1" > report.txt
          echo "" >> report.txt
          
          cat report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: execution-report
          path: report.txt

  generate-report-2:
    needs: [run-2, smoke-2]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Generate Report
        run: |
          echo "Execution Report 2" > report.txt
          cat report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: execution-report
          path: report.txt