name: Go Example POC Workflow

on:
  workflow_dispatch:
    inputs:
      maxRetry:
        description: "Maximum number of retries"
        required: false
        default: "2"

jobs:
  # First Attempt
  setup-environment-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          chmod +x ./scripts/setup-env.sh
          ./scripts/setup-env.sh

  run-go-example-1:
    needs: setup-environment-1
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Go Example
        run: go build -o go-example-bin ./go-example/main.go

      - name: Run Go Example
        id: go-example
        run: |
          ./go-example-bin -p 0
        continue-on-error: true

      - name: Upload Failure Artifact
        if: steps.go-example.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: go-example-fail
          path: go-example-fail.txt

  teardown-environment-1:
    needs: run-go-example-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Teardown Environment
        run: |
          chmod +x ./scripts/teardown-env.sh
          ./scripts/teardown-env.sh

  # Second Attempt
  setup-environment-2:
    needs: 
      - teardown-environment-1
      - run-go-example-1
    runs-on: ubuntu-latest
    if: needs.run-go-example-1.result == 'failure'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          chmod +x ./scripts/setup-env.sh
          ./scripts/setup-env.sh

  run-go-example-2:
    needs: setup-environment-2
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Go Example
        run: go build -o go-example-bin ./go-example/main.go

      - name: Check for Previous Failure Artifact
        id: artifact-check
        uses: actions/download-artifact@v3
        with:
          name: go-example-fail
        continue-on-error: true

      - name: Run Go Example with Artifact
        id: go-example
        run: |
          if [ -f go-example-fail.txt ]; then
            ./go-example-bin -f go-example-fail.txt -p 50
          else
            ./go-example-bin -p 50
          fi
        continue-on-error: true

      - name: Upload Failure Artifact
        if: steps.go-example.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: go-example-fail
          path: go-example-fail.txt

  teardown-environment-2:
    needs: run-go-example-2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Teardown Environment
        run: |
          chmod +x ./scripts/teardown-env.sh
          ./scripts/teardown-env.sh